# Generated by Django 5.1.3 on 2024-11-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stock_images/'),
        ),
        migrations.AlterUniqueTogether(
            name='color',
            unique_together={('name', 'hex_code')},
        ),
    ]
