# Generated by Django 5.1.3 on 2024-12-12 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_sale_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='start_date',
        ),
        migrations.CreateModel(
            name='SaleCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('sales', models.ManyToManyField(related_name='collections', to='store.sale')),
            ],
        ),
    ]
