# Generated by Django 5.1.3 on 2024-12-12 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_sale_end_date_remove_sale_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salecollection',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_collections', to='store.product'),
        ),
    ]
