# Generated by Django 5.1.3 on 2024-12-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_salecollection_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salecollection',
            name='products',
        ),
        migrations.AddField(
            model_name='salecollection',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Products included in this SaleCollection.', related_name='sale_collections', to='store.product'),
        ),
    ]
