# Generated by Django 5.1.3 on 2024-11-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Complete', 'Complete')], default='Pending', max_length=20),
        ),
    ]
