# Generated by Django 5.1.3 on 2024-11-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
