# Generated by Django 5.1.3 on 2024-12-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageview', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homebanner',
            options={'ordering': ['display_order', 'created_at']},
        ),
        migrations.AddField(
            model_name='homebanner',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
